# Generated by Django 4.0.1 on 2022-02-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme_all',
        ),
    ]
