# Generated by Django 4.0.1 on 2022-02-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_theme_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltheme',
            name='fon_color',
        ),
    ]
