# Generated by Django 4.0.1 on 2022-01-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='users',
        ),
    ]
