# Generated by Django 4.0.1 on 2022-02-01 13:39

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_theme_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='fon_color',
            field=colorful.fields.RGBColorField(null=True),
        ),
    ]
