# Generated by Django 4.0.1 on 2022-01-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_date_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_p', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='type_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_post', to='home.typepost'),
        ),
    ]
