# Generated by Django 4.0.1 on 2022-01-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_typepost_alter_post_type_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_post', to='home.typepost'),
        ),
    ]
