# Generated by Django 4.0.1 on 2022-01-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_post_date_alter_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=8)),
                ('background', models.FileField(upload_to='themes')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.theme'),
        ),
    ]
