# Generated by Django 4.0.1 on 2022-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_theme_chat_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='color',
        ),
        migrations.AddField(
            model_name='theme',
            name='color_mes',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_mes_bg',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.FileField(null=True, upload_to='themes'),
        ),
    ]
