# Generated by Django 4.0.1 on 2022-02-01 14:49

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alltheme_fon_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='text_color',
            field=colorful.fields.RGBColorField(null=True),
        ),
    ]
