# Generated by Django 4.0.1 on 2022-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_theme_color_theme_color_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
