# Generated by Django 4.0.1 on 2022-01-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_theme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='music')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='theme',
            name='color_mes',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='color_mes_bg',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, related_name='music_user', to='home.Music'),
        ),
    ]
