# Generated by Django 4.0.1 on 2022-02-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alltheme_coment_img_alltheme_like_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltheme',
            name='coment_img',
            field=models.ImageField(default='comment_imgs/comment.png', null=True, upload_to='theme_all/comment_imgs'),
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='like_img',
            field=models.ImageField(default='like_imgs/like.png', null=True, upload_to='theme_all/like_imgs'),
        ),
    ]
