# Generated by Django 4.0.1 on 2022-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_alltheme_coment_img_alter_alltheme_like_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltheme',
            name='fon_img',
            field=models.ImageField(default=None, null=True, upload_to='theme_all/fon_imgs'),
        ),
    ]
