# Generated by Django 4.0.1 on 2022-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_music_alter_theme_color_mes_alter_theme_color_mes_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='themes',
            field=models.ManyToManyField(null=True, related_name='themes_user', to='home.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
