# Generated by Django 4.0.1 on 2022-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_themes_alter_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_m',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
