# Generated by Django 4.0.1 on 2022-02-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_alltheme_fon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltheme',
            name='fon_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/fon_imgs'),
        ),
    ]
