# Generated by Django 4.0.1 on 2022-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_user_posts_post_user_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_p',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
