# Generated by Django 4.0.1 on 2022-02-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_alltheme_fon_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alltheme',
            old_name='coment_img',
            new_name='comment_img',
        ),
    ]
