# Generated by Django 4.0.1 on 2022-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_message_type_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readeble',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.FileField(default='themes/default.jpg', null=True, upload_to='themes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='themes_user', to='home.Theme'),
        ),
    ]
