# Generated by Django 4.0.1 on 2022-02-03 17:25

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_coment_img_alltheme_comment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='header_bg_color',
            field=colorful.fields.RGBColorField(null=True),
        ),
    ]
