# Generated by Django 4.0.1 on 2022-01-28 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_message_readeble_alter_theme_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
