# Generated by Django 4.0.1 on 2022-01-28 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
