# Generated by Django 4.0.1 on 2022-02-03 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alltheme_header_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='header_bg_opacity',
            field=models.FloatField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
