# Generated by Django 4.0.1 on 2022-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alltheme_header_bg_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='themes_all',
            field=models.ManyToManyField(blank=True, null=True, related_name='themes_all_user', to='home.AllTheme'),
        ),
    ]
