# Generated by Django 4.0.1 on 2022-02-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_user_themes_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='themes_all',
        ),
    ]
