# Generated by Django 4.0.1 on 2022-02-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_user_themes_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_m', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='comment_img',
            field=models.ImageField(default='theme_all/comment_imgs/comment.png', null=True, upload_to='theme_all/comment_imgs'),
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='like_img',
            field=models.ImageField(default='theme_all/like_imgs/like.png', null=True, upload_to='theme_all/like_imgs'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_mes', to='home.typemes'),
        ),
    ]
