# Generated by Django 4.0.1 on 2022-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_message_type_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type_m',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
