# Generated by Django 4.0.1 on 2022-02-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_message_type_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_mes', to='home.typemes'),
        ),
    ]
