# Generated by Django 4.0.1 on 2022-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_message_type_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemes',
            name='data_m',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
