# Generated by Django 4.0.1 on 2022-02-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_typemes_data_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemes',
            name='data_m',
        ),
    ]
