# Generated by Django 4.0.1 on 2022-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_theme_color_mes_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='back_img',
            field=models.ImageField(default='theme_all/like_imgs/back.png', null=True, upload_to='theme_all/back_imgs'),
        ),
    ]
