# Generated by Django 4.0.1 on 2022-02-14 10:32

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alltheme_back_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='text_input_color',
            field=colorful.fields.RGBColorField(null=True),
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='back_img',
            field=models.ImageField(default='theme_all/back_imgs/back.png', null=True, upload_to='theme_all/back_imgs'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.theme'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_file_mes', to='home.typefile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_mes', to='home.typemes'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_file_post', to='home.typefile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pub_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme_all',
            field=models.ForeignKey(blank=True, default=home.models.def_all_theme, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='theme_all_user', to='home.alltheme'),
        ),
    ]
