# Generated by Django 4.0.1 on 2022-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_alltheme_text_input_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
