# Generated by Django 4.0.1 on 2022-02-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_alltheme_back_img_alter_alltheme_comment_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='music_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/music_imgs'),
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='back_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/back_imgs'),
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='comment_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/comment_imgs'),
        ),
        migrations.AlterField(
            model_name='alltheme',
            name='like_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/like_imgs'),
        ),
    ]
