# Generated by Django 4.0.1 on 2022-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alltheme_music_img_alter_alltheme_back_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefile',
            name='type_f_magic',
            field=models.TextField(null=True),
        ),
    ]
