# Generated by Django 4.0.1 on 2022-02-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='themes_all',
            field=models.ManyToManyField(blank=True, null=True, related_name='themes_all_user', to='home.AllTheme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.FileField(blank=True, default=None, null=True, upload_to='themes'),
        ),
    ]
