# Generated by Django 4.0.1 on 2022-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_user_themes_all_alter_theme_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music_shared',
            field=models.ManyToManyField(blank=True, null=True, related_name='music_shared_user', to='home.Music'),
        ),
    ]
