# Generated by Django 4.0.1 on 2022-02-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_user_music_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saves_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='save_post_user', to='home.Post'),
        ),
    ]
