# Generated by Django 4.0.1 on 2022-03-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlist_user', to='home.Playlist'),
        ),
    ]
