# Generated by Django 4.0.1 on 2022-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_user_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='playlists'),
        ),
    ]
