# Generated by Django 4.0.1 on 2022-03-06 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_playlist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_playlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='img',
            field=models.ImageField(default=None, upload_to='playlists'),
        ),
    ]
