# Generated by Django 4.0.1 on 2022-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_playlist_autor_playlist_date_alter_playlist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='img',
            field=models.ImageField(default=None, upload_to='playlists_img'),
        ),
    ]
