# Generated by Django 4.0.1 on 2022-03-10 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_messageactivity_user_message_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageactivity',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageactivity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_activity_file'),
        ),
    ]
