# Generated by Django 4.0.1 on 2022-03-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_messageactivity_type_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageactivity',
            name='file',
        ),
        migrations.RemoveField(
            model_name='messageactivity',
            name='type_f',
        ),
        migrations.AddField(
            model_name='messageactivity',
            name='id_media',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageactivity',
            name='type_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_mesa', to='home.typemes'),
        ),
    ]
