# Generated by Django 4.0.1 on 2022-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_messageactivity_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageactivity',
            name='id_media',
        ),
        migrations.AddField(
            model_name='messageactivity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_activity_file'),
        ),
    ]
