# Generated by Django 4.0.1 on 2022-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_messageactivity_type_m_messageactivity_type_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='add_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/add_img'),
        ),
    ]
