# Generated by Django 4.0.1 on 2022-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alltheme_activity_img_alltheme_ai_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='music_share_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/music_share_img'),
        ),
    ]
