# Generated by Django 4.0.1 on 2022-04-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alltheme_music_share_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltheme',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='chats_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='comment_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='file_send_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='find_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='fon_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='friends_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='like_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='menu_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='music_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='music_share_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='no_media_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='options_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='pause_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='play_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='play_in_all_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='save_img',
        ),
        migrations.RemoveField(
            model_name='alltheme',
            name='settings_img',
        ),
    ]
