# Generated by Django 4.0.1 on 2022-04-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_remove_chat_users_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
