# Generated by Django 4.0.1 on 2022-04-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_chat_friend_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.theme'),
        ),
    ]
