# Generated by Django 4.0.1 on 2022-04-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_chat_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='friend',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_friend_chat', to='home.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.theme'),
        ),
    ]
