# Generated by Django 4.0.1 on 2022-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_user_playlists_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='end_scroll_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/end_scroll_img'),
        ),
        migrations.AddField(
            model_name='alltheme',
            name='music_left_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/music_left_img'),
        ),
        migrations.AddField(
            model_name='alltheme',
            name='music_right_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/music_right_img'),
        ),
    ]
