# Generated by Django 4.0.1 on 2022-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alltheme_end_scroll_img_alltheme_music_left_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
