# Generated by Django 4.0.1 on 2022-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alltheme_close_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='turn_over_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/turn_over_img'),
        ),
    ]
