# Generated by Django 4.0.5 on 2022-06-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_complainpost_delete_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltheme',
            name='ai_img',
        ),
    ]
