# Generated by Django 4.0.5 on 2022-06-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_remove_alltheme_ai_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emoji',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_parent', to='home.message'),
        ),
    ]
