# Generated by Django 4.0.5 on 2022-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_message_emoji_message_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emoji',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
