# Generated by Django 4.0.5 on 2022-06-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_alter_message_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emoji',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
