# Generated by Django 4.0.5 on 2022-06-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_alter_message_type_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emoji',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
