# Generated by Django 4.0.5 on 2022-06-21 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_comment_date_alter_complainpost_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emoji',
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoji_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='emoji',
            field=models.ManyToManyField(blank=True, null=True, related_name='emoji_mess', to='home.emoji'),
        ),
    ]
