# Generated by Django 4.0.5 on 2022-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltheme',
            name='microphone_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme_all/microphone_img'),
        ),
    ]
