# Generated by Django 4.0.5 on 2022-06-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alltheme_microphone_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageactivity',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
